### PR TITLE
Added initial workflow configuration for tests

### PR DESCRIPTION
**Pull request by gridhead**
Signed-off-by: Akashdeep Dhar <akashdeep.dhar@gmail.com>

### CODE REVIEW

**Comment by gridhead** [comment]
In one of the local checks, it was discovered that `gssapi` of the said version requires `libkrb5-dev` package to be installed on Ubuntu in order for the dependencies to be satisfied or else errors can be encountered, leading to failed checks[1]. Obligatorily added that package as a part of the subsequent commit[2].

I have created a PR against the `develop` branch of my own fork for testing and the checks ran just fine[3]. Let me know if there are any changes needed.

[1] 
```shell
...
Collecting gssapi<2.0.0,>=1.5.1
  Downloading gssapi-1.6.12.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 77 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8cjvjp13/gssapi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8cjvjp13/gssapi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-8cjvjp13/gssapi/pip-egg-info
         cwd: /tmp/pip-install-8cjvjp13/gssapi/
    Complete output (13 lines):
    /bin/sh: 1: krb5-config: not found
    In distributed package, building from C files...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8cjvjp13/gssapi/setup.py", line 109, in <module>
        link_args = shlex.split(get_output(f"{kc} --libs gssapi"))
      File "/tmp/pip-install-8cjvjp13/gssapi/setup.py", line 34, in get_output
        res = subprocess.check_output(*args, shell=True, **kwargs)
      File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.8/subprocess.py", line 512, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command 'krb5-config --libs gssapi' returned non-zero exit status 127.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
...
```

[2] In https://github.com/fedora-infra/fedbadges/pull/81/commits/08c34c19b9927218f5664d97b669247e49f3b839, I added a `sudo apt install libkrb5-dev -y` immediately before installing the dependencies from pip3.

[3] Self-check can be found here https://github.com/t0xic0der/fedbadges/pull/1/checks?check_run_id=2435097631.

CC @mscherer @sayanchowdhury

**Review by laxathom — APPROVED** [review]
Looks good to me.

**Comment by nbebout** [comment]
:+1:

**Review by sayanchowdhury — APPROVED** [review]
LGTM. Let's merge!

**Pull request merged**
