### PR TITLE
Migrate to python 3 and Badgr

### PR DESCRIPTION
**Pull request by snehalbaghel**
There is 1 TODO in this PR:

1) Handling images (See concentricsky/badgr-server#312)

### CODE REVIEW

**Comment by laxathom** [comment]
Hey @snehalbaghel , do you actually need to have those to TODOs done to merge this PR or can we open issues against them to work on this later on?
Note that merging this PR doesn't mean we will release a new version but it would help to have this code change for additional work that requires it.

**Comment by snehalbaghel** [comment]
Hey @laxathom yeah, I was under the impression merge would be a release. In this case, we can merge it. I can work on the second todo this week(end) although the first one would require some rethinking cause the PR at badgr-server isn't merged.

**Comment by gridhead** [comment]
Thank you @snehalbaghel.

Once we are done with merging the Python 3 port, we can go ahead with implementing the Tox checks with GitHub Actions.

**Comment by laxathom** [comment]
> Hey @laxathom yeah, I was under the impression merge would be a release. In this case, we can merge it. I can work on the second todo this week(end) although the first one would require some rethinking cause the PR at badgr-server isn't merged.

Excellent!. Do you need additional review on the PR at badgr-server or @ottonomy is the only one who can process it?

**Comment by snehalbaghel** [comment]
> Excellent!. Do you need additional review on the PR at badgr-server or @ottonomy is the only one who can process it?

Yeah I think only they can process it.

If the PR over there can't be merged we will have to encode our images and pass it as a base64 data uri meaning we won't be able to manage images through the fedora-badges repo like how we do now.

For now I've fixed the race condition let me know if you think sending images as base64 is viable for us, I can make a seprate PR for that.

**Comment by snehalbaghel** [comment]
@laxathom @t0xic0der can you review this?

**Review by laxathom — APPROVED** [review]
Looks good to me.

**Comment by gridhead** [comment]
> @laxathom @t0xic0der can you review this?

A bit caught up here @snehalbaghel. I think @laxathom's approval should suffice here. :slightly_smiling_face:

**Comment by gridhead** [comment]
@laxathom @snehalbaghel I think this can be merged now that @laxathom has given a +1 (or do we need more reviews?)

Any of you folks have the push rights to the repo?

**Comment by gridhead** [comment]
Thanks @mscherer.

**Pull request merged**
