### PR TITLE
A diagram for how fedbadges relates to the other badges.fp.o pieces.

### PR DESCRIPTION
**Pull request by ralphbean**
For https://fedoraproject.org/wiki/Infrastructure/Debt/2016/March

### CODE REVIEW

**Comment by pypingou** [comment]
Looks good to me, my only comment would be if we could find a way to have only one `tahrir api` block instead of 4.

**Comment by ralphbean** [comment]
Hm.  Maybe I can make it work.. but I don't want to accidentally convey the mistaken notion that `tahrir api` is a service that all the other services interact with.  It's a module that ends up being embedded in all the other processes, which they use to interact with the DB in a hopefully consistent way.

**Comment by ralphbean** [comment]
Yeah - thinking over it more, @pypingou I'd really like to keep the blocks separate -- again, just to convey that tahrir-api is not a service, but a library.

**Comment by pypingou** [comment]
ok wfm, :+1:

**Pull request merged**
